// <auto-generated />
using Baguettes.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Baguettes.Core.Migrations
{
    [DbContext(typeof(BaguetteDbContext))]
    [Migration("20250327133910_AddBaguetteData")]
    partial class AddBaguetteData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Baguettes.Core.Entities.Baguette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Baguettes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Classic French baguette with a crispy crust.",
                            Name = "Traditional Baguette"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Healthy whole wheat variation of the classic baguette.",
                            Name = "Whole Wheat Baguette"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tangy sourdough baguette with a chewy texture.",
                            Name = "Sourdough Baguette"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Baguette infused with roasted garlic flavors.",
                            Name = "Garlic Baguette"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
